name: Compilar JAR

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Encontrar Gradle
        run: |
          GRADLEW=$(find . -type f -name gradlew | head -n 1)

          if [ -z "$GRADLEW" ]; then
            echo "ERROR: No se encontró gradlew"
            exit 1
          fi

          PROJECT_DIR=$(dirname "$GRADLEW")

          echo "Proyecto encontrado: $PROJECT_DIR"

          chmod +x "$GRADLEW"

          echo "PROJECT_DIR=$PROJECT_DIR" >> "$GITHUB_ENV"

      - name: Compilar JAR
        run: |
          cd "$PROJECT_DIR"
          ./gradlew build --no-daemon

      - name: Entregar JAR
        uses: actions/upload-artifact@v4
        with:
          name: GalloGiro-JAR
          path: "**/build/libs/*.jar"
          if-no-files-found: error
